algoritmo "aula3media"
// Função :
// Autor :
// Data : 22/11/2024
// Seção de Declarações 
var
   valor1, valor2, media: Real
inicio
// Seção de Comandos
   Escreval("Digite o primeiro valor")
   Leia(valor1)
   Escreval ()
   Escreval ("Digite o segundo valor")
   Leia(valor2)
   media <- (valor1 + valor2) /2
   Escreval("O resultado da media entre ", valor1, " e ", valor2, " é ", media)
fimalgoritmo
